import { Heading, HStack } from '@chakra-ui/react'
import { BigTextInfo } from '../molecules/BigTextInfo'
import { Section } from '../templates/Section'

export function BigInfoSection() {
	return (
		<Section bgColor='primary.200'>
			<Heading mb='3rem'>
				Better machine performance for better <br />
				maintenance team&apos;s productivity
			</Heading>

			<HStack spacing='5rem'>
				<BigTextInfo
					bigText='90%'
					description='ASSERTIVENESS OF INSIGHTS GENERATED BY TRACTIAN PLATFORM.'
				/>
				<BigTextInfo
					bigText='45%'
					description='	INCREASED RELIABILITY OF MACHINES WITH TRACTIAN SOLUTION.'
				/>
				<BigTextInfo
					bigText='30%'
					description='REDUCTION OF LAST-MINUTE MAINTENANCE OCCURRENCES.'
				/>
			</HStack>
		</Section>
	)
}
